-- Question table (matches the Question entity)
CREATE TABLE question (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category         VARCHAR(255),
    difficulty_level VARCHAR(255),
    option1          VARCHAR(255),
    option2          VARCHAR(255),
    option3          VARCHAR(255),
    option4          VARCHAR(255),
    question_title   VARCHAR(255),
    right_answer     VARCHAR(255)
);