-- Quiz table (matches the Quiz entity)
CREATE TABLE quiz (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255)
);

-- Element collection for Quiz.questionIds
CREATE TABLE quiz_question_ids (
    quiz_id      INTEGER NOT NULL,
    question_ids INTEGER,
    CONSTRAINT fk_quiz_question_ids_quiz FOREIGN KEY (quiz_id) REFERENCES quiz(id)
);